ServerConfiguration:
  #These set the values of all pre-defined messages. If you would like to disable use null. Use & for colour codes.
  #Use API enum colour codes, anything else is will use the default colour.
  Predefined_Messages:
    LOBBYCMDS_CONSOLE_ENABLED:
      Text: "<PluginName> has been enabled!"
      Colour: NONE
    LOBBYCMDS_CONSOLE_DISABLED:
      Text: null
      Colour: NONE
    LOBBY_PLAYER_PROCESSING:
      Text: null
      Colour: NONE
    LOBBY_PLAYER_REQUEST_ACCEPTED:
      Text: null
      Colour: NONE
    LOBBY_PLAYER_REQUEST_DENIED:
      Text: null
      Colour: NONE
    LOBBY_CONSOLE_DENIED:
      Text: null
      Colour: NONE
