ServerConfiguration:
  #These set the values of all pre-defined messages. If you would like to disable use null. Use & for colour codes.
  #Use API enum colour codes, anything else is will use the default colour.
  Predefined_Messages:
    LobbyCmdsConsoleEnabledMessage:
      Text: "<PluginName> has been enabled!"
      Colour: NONE
    LobbyCmdsConsoleDisabledMessage:
      Text: null
      Colour: NONE
    LobbyCommandProcessing:
      Text: null
      Colour: NONE
    LobbyCommandAccepted:
      Text: null
      Colour: NONE
    LobbyCommandDenied:
      Text: null
      Colour: NONE
    LobbyCommandConsole:
      Text: null
      Colour: NONE
